on:
  push:
    branches: [ "main" ]
    # Workflow uruchomi się TYLKO gdy zmienisz pliki w tym folderze:
    paths:
      - 'Laboratorium 3/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Laboratorium 3/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Ustawienie domyślnego katalogu dla wszystkich kroków "run" w tym zadaniu
    defaults:
      run:
        working-directory: ./Laboratorium 3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      # Ten krok wykona się już wewnątrz folderu 'NazwaTwojegoFolderu'
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        
    - name: Test with pytest
      # Pytest uruchomi się wewnątrz folderu, więc zobaczy tylko testy gry
      # i nie będzie próbował importować Selenium z innych folderów
      run: |
        pytest
